version: 2
workdir: .

components:
  platform:    { in: "internal/platform/**" }
  identity:    { in: "internal/modules/identity/**" }
  tenant:      { in: "internal/modules/tenant/**" }
  catalog:     { in: "internal/modules/catalog/**" }
  pos:         { in: "internal/modules/pos/**" }
  inventory:   { in: "internal/modules/inventory/**" }
  billing:     { in: "internal/modules/billing/**" }
  payment:     { in: "internal/modules/payment/**" }
  edge_sync:   { in: "internal/modules/edge_sync/**" }

deps:
  identity:
    may_depend_on: [platform]
  tenant:
    may_depend_on: [platform]
  catalog:
    may_depend_on: [platform]
  inventory:
    may_depend_on: [platform, catalog.public]
    must_not_depend_on: [pos.domain, payment.domain, pos.repo, payment.repo]
  pos:
    may_depend_on: [platform, catalog.public, inventory.public, payment.public]
    must_not_depend_on: [inventory.repo, inventory.domain, billing.domain, catalog.domain, payment.repo]
  payment:
    may_depend_on: [platform]
    must_not_depend_on: [pos.domain, pos.repo, billing.domain]
  billing:
    may_depend_on: [platform]
    must_not_depend_on: [pos.domain, payment.domain, pos.repo, payment.repo]
  edge_sync:
    may_depend_on: [platform, catalog.public, pos.public, inventory.public]
    must_not_depend_on: [pos.repo, pos.domain, catalog.domain, inventory.domain]
