// Wire <-> domain translation for the `fiscal:branch-pending` Wails event.
//
// Deliberately in lib/ rather than next to the hook that consumes it: the hook
// imports `../../wailsjs/runtime/runtime`, which is GENERATED by
// `wails generate module` and gitignored (see pos-desktop/.gitignore). A test
// importing anything from the hook module therefore fails on a fresh clone —
// including in CI, which never runs the Wails generator. Keeping the pure part
// here means these rules stay testable without the generated bindings on disk.

import type { RemotePendingFiscal, RemoteSettledFiscal } from './fiscalStatus'

/** Wire shape of the `fiscal:branch-pending` event — mirrors
 * BranchPendingFiscalDTO in fiscal_poller.go. Declared by hand because this
 * payload travels as an untyped Wails EVENT, not a binding return value, so it
 * does not appear in the generated wailsjs/go/models.ts. */
export type BranchFiscalPendingEvent = {
  branch_id: string
  as_of: string
  pending?: Array<{
    payment_id: string
    check_id: string
    amount_total: number
    registered_at: string
    age_seconds: number
  }>
  recently_settled?: Array<{
    payment_id: string
    check_id: string
    status: string
    /** Contract addendum: settled items carry their amount, so a payment
     * completed at another till can be credited here instead of snapping back
     * into "kalan" (see fiscalStatus.ts's remoteCompletedOnly). */
    amount_total: number
    failure_reason?: string
    settled_at: string
  }>
}

export type BranchFiscalPending = {
  pending: RemotePendingFiscal[]
  recentlySettled: RemoteSettledFiscal[]
}

export const EMPTY_BRANCH_FISCAL: BranchFiscalPending = { pending: [], recentlySettled: [] }

/** Narrows a settled item's status. An unrecognized value is dropped rather
 * than guessed: this list only drives a failure banner, and inventing a
 * `failed` from an unknown string would alarm a cashier over nothing. */
function parseSettledStatus(raw: string): RemoteSettledFiscal['status'] | null {
  return raw === 'completed' || raw === 'failed' || raw === 'voided' ? raw : null
}

/**
 * Coerces a numeric wire field. Every number this event carries is either
 * subtracted from what the cashier may still collect (`amount_total`) or shown
 * as elapsed time (`age_seconds`), so a missing/garbage value must become 0 —
 * never NaN, which propagates through every downstream total and blanks the
 * whole money column instead of failing visibly.
 */
function toFiniteNumber(raw: unknown): number {
  return typeof raw === 'number' && Number.isFinite(raw) ? raw : 0
}

export function parseBranchFiscalEvent(
  evt: BranchFiscalPendingEvent | null | undefined,
): BranchFiscalPending {
  const pending: RemotePendingFiscal[] = (evt?.pending ?? []).map((p) => ({
    paymentId: p.payment_id,
    checkId: p.check_id,
    amountTotal: toFiniteNumber(p.amount_total),
    ageSeconds: toFiniteNumber(p.age_seconds),
  }))

  const recentlySettled: RemoteSettledFiscal[] = []
  for (const s of evt?.recently_settled ?? []) {
    const status = parseSettledStatus(s.status)
    if (!status) continue
    recentlySettled.push({
      paymentId: s.payment_id,
      checkId: s.check_id,
      status,
      amountTotal: toFiniteNumber(s.amount_total),
      failureReason: s.failure_reason || undefined,
    })
  }

  return { pending, recentlySettled }
}
