import tseslint from "typescript-eslint"
import reactPlugin from "eslint-plugin-react"
import onlinemenuEslint from "@onlinemenu/config/eslint"

/**
 * pos-desktop henüz Next.js'e bağlı değil (Wails webview) — bu yüzden
 * `eslint-config-next` yerine yalnızca `typescript-eslint` +
 * `eslint-plugin-react` doğrudan register edilir (bkz. packages/ui-kit).
 *
 * lessons-from-b2b Bölüm 5 — "Tek token-refresh yolu": webview HTTP
 * yapmaz, yalnızca Wails binding'leri (../wailsjs/go/main/App) üzerinden Go
 * tarafını çağırır. Token'ları saklayan ve backend'e konuşan tek yer
 * internal/apiclient (Go); bu kural burada prose olarak kalmasın diye
 * `fetch`/`XMLHttpRequest`/`axios` kullanımı bu app'te lint hatası olarak
 * zorlanır — b2b'de aynı kural yalnızca CLAUDE.md'de yazıyordu ve iki
 * bağımsız interceptor aynı config dosyasına yarışıyordu.
 *
 * @type {import("eslint").Linter.Config[]}
 */
const NO_DIRECT_HTTP_MESSAGE =
  "pos-desktop webview HTTP yapamaz (docs/lessons-from-b2b.md #5, Tek token-refresh yolu). " +
  "Backend çağrıları yalnızca Wails binding'leri (../wailsjs/go/main/App) üzerinden, Go " +
  "internal/apiclient.Client aracılığıyla yapılır."

const config = [
  ...onlinemenuEslint.base,
  {
    // Generated by `wails generate module` / `wails build` — not
    // hand-written, not linted (matches the *.gen.ts convention in base).
    ignores: ["wailsjs/**"],
  },
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    plugins: { react: reactPlugin },
    settings: { react: { version: "19" } },
    rules: {
      ...reactPlugin.configs.recommended.rules,
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
    },
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-globals": [
        "error",
        { name: "fetch", message: NO_DIRECT_HTTP_MESSAGE },
        { name: "XMLHttpRequest", message: NO_DIRECT_HTTP_MESSAGE },
      ],
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "axios", message: NO_DIRECT_HTTP_MESSAGE },
            { name: "node-fetch", message: NO_DIRECT_HTTP_MESSAGE },
          ],
        },
      ],
    },
  },
]

export default config
