package auth

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/google/uuid"
	"github.com/open-policy-agent/opa/v1/rego"
	"github.com/stretchr/testify/require"
)

// ---------------------------------------------------------------------------
// Build-time permission matrix for the admin UI (docs/lessons-from-b2b.md §4,
// role helper drift).
//
// web/apps/admin/src/lib/permissions.ts used to hold a hand-written mirror of
// a handful of authz.rego rules and treated every other action as ALLOWED.
// Screens the backend 403s were therefore rendered for every role. This test
// replaces that mirror with a file generated from the real compiled policy:
// every system role x every action the backend knows is evaluated through
// Engine.Decide and written to permissionMatrixPath.
//
// ADR-AUTH-001 still holds: there is no runtime endpoint that lists
// permissions. The matrix is a build artefact describing the policy for the
// well-known system roles, the same thing a reader of authz.rego would learn.
//
// Regenerate with `task authz:gen` (sets UPDATE_PERMISSION_MATRIX=1). Without
// the variable the test compares and FAILS when the committed file is stale,
// which is the CI gate: a rego change that is not reflected in the UI matrix
// cannot merge. It deliberately does not skip under -short.
// ---------------------------------------------------------------------------

const (
	permissionMatrixPath = "../../../../web/apps/admin/src/generated/permission-matrix.json"
	authzRegoPath        = "../../../configs/opa/bundles/authz.rego"
	modulesRoot          = "../../modules"
	updateMatrixEnv      = "UPDATE_PERMISSION_MATRIX"
)

// actionLiteral matches a "<module>.<resource>.<verb>" action string.
var actionLiteral = regexp.MustCompile(`"([a-z][a-z_-]*\.[a-z][a-z_]*\.[a-z][a-z_]*)"`)

type permissionMatrix struct {
	Comment string `json:"_comment"`
	// Roles maps well-known system role id -> system_key.
	Roles map[string]string `json:"roles"`
	// Scopes is the data visibility OPA returns for a principal holding only
	// that role ("tenant" | "branch" | "own").
	Scopes map[string]string `json:"scopes"`
	// Actions maps every known action -> sorted system roles allowed it.
	Actions map[string][]string `json:"actions"`
}

// regoActions returns every action literal named in the policy, including the
// rules that no route uses yet (they still describe who may do what).
func regoActions(t *testing.T) []string {
	t.Helper()
	raw, err := os.ReadFile(authzRegoPath)
	require.NoError(t, err)

	var out []string
	for _, line := range strings.Split(string(raw), "\n") {
		code, _, _ := strings.Cut(line, "#")
		for _, m := range actionLiteral.FindAllStringSubmatch(code, -1) {
			out = append(out, m[1])
		}
	}
	return out
}

// callSiteActions returns every action literal in the transport and service
// layers of every module — the strings handlers hand to permit(...) /
// RequirePermission / Engine.Decide. Tests are excluded: they deliberately
// probe actions that do not exist (e.g. pos.check.delete).
func callSiteActions(t *testing.T) []string {
	t.Helper()
	var out []string
	err := filepath.WalkDir(modulesRoot, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		layer := filepath.Base(filepath.Dir(path))
		if layer != "http" && layer != "service" {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, line := range strings.Split(string(raw), "\n") {
			if strings.HasPrefix(strings.TrimSpace(line), "//") {
				continue
			}
			for _, m := range actionLiteral.FindAllStringSubmatch(line, -1) {
				out = append(out, m[1])
			}
		}
		return nil
	})
	require.NoError(t, err)
	return out
}

func buildPermissionMatrix(t *testing.T) permissionMatrix {
	t.Helper()
	eng := newTestEngine(t)
	ctx := context.Background()

	vocab := map[string]struct{}{}
	for _, a := range append(regoActions(t), callSiteActions(t)...) {
		vocab[a] = struct{}{}
	}
	require.NotEmpty(t, vocab)

	m := permissionMatrix{
		Comment: "GENERATED by backend/internal/platform/auth/permission_matrix_test.go " +
			"from configs/opa/bundles/authz.rego — do not edit. Regenerate: task authz:gen",
		Roles:   map[string]string{},
		Scopes:  map[string]string{},
		Actions: map[string][]string{},
	}

	for id, name := range seedRoleUUIDs {
		m.Roles[id] = name
	}

	for action := range vocab {
		allowed := []string{}
		for id, name := range seedRoleUUIDs {
			p := Principal{
				PersonID: uuid.New(),
				Ctx:      ContextStaff,
				TenantID: uuid.New(),
				BranchID: uuid.New(),
				RoleIDs:  []uuid.UUID{uuid.MustParse(id)},
			}
			d, err := decideUncached(ctx, eng, action, p)
			require.NoError(t, err)
			if d.Allow {
				allowed = append(allowed, name)
				m.Scopes[name] = d.Scope
			}
		}
		sort.Strings(allowed)
		m.Actions[action] = allowed
	}

	// A role that holds no action at all still gets its scope recorded.
	for id, name := range seedRoleUUIDs {
		if _, ok := m.Scopes[name]; ok {
			continue
		}
		d, err := decideUncached(ctx, eng, "__scope_probe__.none.none", Principal{
			PersonID: uuid.New(), Ctx: ContextStaff, TenantID: uuid.New(), BranchID: uuid.New(),
			RoleIDs: []uuid.UUID{uuid.MustParse(id)},
		})
		require.NoError(t, err)
		m.Scopes[name] = d.Scope
	}
	return m
}

// decideUncached evaluates the prepared policy query exactly as Engine.Decide
// does, minus the Redis round trip: ~1000 evaluations against the unreachable
// test Redis would otherwise pay go-redis' retry backoff on every call.
func decideUncached(ctx context.Context, eng *Engine, action string, p Principal) (Decision, error) {
	roles := make([]string, len(p.RoleIDs))
	for i, id := range p.RoleIDs {
		roles[i] = id.String()
	}
	results, err := eng.query.Eval(ctx, rego.EvalInput(opaInput{
		Action: action,
		Principal: principal{
			Sub: p.PersonID.String(), TenantID: p.TenantID.String(),
			BranchIDs: []string{p.BranchID.String()}, Roles: roles,
		},
	}))
	if err != nil || len(results) == 0 || len(results[0].Expressions) == 0 {
		return Decision{}, err
	}
	raw, _ := results[0].Expressions[0].Value.(map[string]interface{})
	d := Decision{}
	d.Allow, _ = raw["allow"].(bool)
	d.Scope, _ = raw["scope"].(string)
	return d, nil
}

func encodePermissionMatrix(t *testing.T, m permissionMatrix) []byte {
	t.Helper()
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	require.NoError(t, enc.Encode(m))
	return buf.Bytes()
}

func TestPermissionMatrix_GeneratedFileIsCurrent(t *testing.T) {
	m := buildPermissionMatrix(t)

	// Sanity: the manager wildcard must reach every action. If it stops doing
	// so, the policy changed shape and the UI matrix is not the only casualty.
	for action, roles := range m.Actions {
		require.Contains(t, roles, "manager", "manager wildcard lost %s", action)
	}

	want := encodePermissionMatrix(t, m)

	if os.Getenv(updateMatrixEnv) == "1" {
		require.NoError(t, os.MkdirAll(filepath.Dir(permissionMatrixPath), 0o755))
		require.NoError(t, os.WriteFile(permissionMatrixPath, want, 0o644)) //nolint:gosec // generated, world-readable source file
		return
	}

	got, err := os.ReadFile(permissionMatrixPath)
	require.NoError(t, err, "permission matrix missing — run `task authz:gen`")
	require.Equal(t, string(want), string(got),
		"web/apps/admin/src/generated/permission-matrix.json is stale — run `task authz:gen` and commit the result")
}
