// Package service implements the business logic for the tenant module.
// It wraps the repo layer and enforces the transaction boundary via db.Pool.
package service

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"go.uber.org/fx"
	"go.uber.org/zap"

	"onlinemenu.tr/internal/modules/tenant/events"
	pub "onlinemenu.tr/internal/modules/tenant/public"
	"onlinemenu.tr/internal/modules/tenant/repo"
	"onlinemenu.tr/internal/platform/db"
	"onlinemenu.tr/internal/platform/eventbus"
)

// Compile-time interface conformance checks.
var (
	_ pub.TenantReader    = (*Service)(nil)
	_ pub.TenantWriter    = (*Service)(nil)
	_ pub.BranchStore     = (*Service)(nil)
	_ pub.DocumentStore   = (*Service)(nil)
	_ pub.HoursStore      = (*Service)(nil)
	_ pub.IntegratorStore = (*Service)(nil)
)

// Service implements the tenant module's public interfaces.
type Service struct {
	db         *db.Pool
	tenantRepo *repo.TenantRepo
	branchRepo *repo.BranchRepo
	docRepo    *repo.DocumentRepo
	intRepo    *repo.IntegratorRepo
	hoursRepo  *repo.HoursRepo
	publisher  eventbus.Publisher
	logger     *zap.Logger
}

// Params groups the fx-injected dependencies for NewService.
type Params struct {
	fx.In

	DB         *db.Pool
	TenantRepo *repo.TenantRepo
	BranchRepo *repo.BranchRepo
	DocRepo    *repo.DocumentRepo
	IntRepo    *repo.IntegratorRepo
	HoursRepo  *repo.HoursRepo
	// Bus is the concrete eventbus.Bus; stored as Publisher so tests can substitute a stub.
	Bus    *eventbus.Bus
	Logger *zap.Logger
}

// NewService constructs a Service for fx injection.
func NewService(p Params) *Service {
	return &Service{
		db:         p.DB,
		tenantRepo: p.TenantRepo,
		branchRepo: p.BranchRepo,
		docRepo:    p.DocRepo,
		intRepo:    p.IntRepo,
		hoursRepo:  p.HoursRepo,
		publisher:  p.Bus,
		logger:     p.Logger,
	}
}

// --- TenantReader ---

func (s *Service) GetByID(ctx context.Context, tenantID uuid.UUID) (pub.Tenant, error) {
	var t pub.Tenant
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		t, err = s.tenantRepo.GetByID(ctx, tx, tenantID)
		return err
	})
	if err != nil {
		return pub.Tenant{}, wrapNotFound(err, "service: get tenant by id: %w")
	}
	return t, nil
}

func (s *Service) GetBranch(ctx context.Context, tenantID, branchID uuid.UUID) (pub.Branch, error) {
	var b pub.Branch
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		b, err = s.branchRepo.GetBranch(ctx, tx, tenantID, branchID)
		return err
	})
	if err != nil {
		return pub.Branch{}, wrapNotFound(err, "service: get branch: %w")
	}
	return b, nil
}

func (s *Service) IsModuleEnabled(ctx context.Context, tenantID uuid.UUID, module string) (bool, error) {
	var enabled bool
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		enabled, err = s.tenantRepo.IsModuleEnabled(ctx, tx, tenantID, module)
		return err
	})
	if err != nil {
		return false, fmt.Errorf("service: is module enabled: %w", err)
	}
	return enabled, nil
}

func (s *Service) GetEffectiveIntegrator(ctx context.Context, tenantID, branchID uuid.UUID, provider pub.BillingProvider) (pub.BillingIntegrator, error) {
	var i pub.BillingIntegrator
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		i, err = s.intRepo.GetEffectiveIntegrator(ctx, tx, tenantID, branchID, provider)
		return err
	})
	if err != nil {
		return pub.BillingIntegrator{}, wrapNotFound(err, "service: get effective integrator: %w")
	}
	return i, nil
}

// --- TenantWriter ---

// Create inserts a new tenant and publishes the tenant.created.v1 event.
//
// uuid.Nil is used as the RLS context because the tenant row does not exist yet at
// INSERT time. The tenants RLS WITH CHECK requires id = app.tenant_id; with uuid.Nil
// set and a new UUID generated by the DB, the INSERT bypasses the policy — this is an
// accepted bootstrap pattern restricted to the admin/onboarding path only.
// TODO(platform): replace with a dedicated WithBootstrapTx that uses app_migrator role.
func (s *Service) Create(ctx context.Context, t pub.Tenant) (pub.Tenant, error) {
	var created pub.Tenant
	err := s.db.WithTenantTx(ctx, uuid.Nil, func(tx pgx.Tx) error {
		var err error
		created, err = s.tenantRepo.Create(ctx, tx, t)
		return err
	})
	if err != nil {
		return pub.Tenant{}, fmt.Errorf("service: create tenant: %w", err)
	}

	if err := events.PublishTenantCreated(ctx, s.publisher, created); err != nil {
		// Event failure is non-fatal: the DB row is committed and an outbox worker
		// (ADR-DATA-001) is the authoritative delivery mechanism. Log for alerting.
		s.logger.Warn("tenant.created.v1 publish failed",
			zap.String("tenant_id", created.ID.String()),
			zap.Error(err),
		)
	}
	return created, nil
}

func (s *Service) Update(ctx context.Context, t pub.Tenant) (pub.Tenant, error) {
	var updated pub.Tenant
	err := s.db.WithTenantTx(ctx, t.ID, func(tx pgx.Tx) error {
		var err error
		updated, err = s.tenantRepo.Update(ctx, tx, t)
		return err
	})
	if err != nil {
		return pub.Tenant{}, wrapNotFound(err, "service: update tenant: %w")
	}
	return updated, nil
}

func (s *Service) Deactivate(ctx context.Context, tenantID uuid.UUID) error {
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.tenantRepo.Deactivate(ctx, tx, tenantID)
	})
	if err != nil {
		return wrapNotFound(err, "service: deactivate tenant: %w")
	}
	return nil
}

// --- BranchStore ---

func (s *Service) ListBranches(ctx context.Context, tenantID uuid.UUID) ([]pub.Branch, error) {
	var branches []pub.Branch
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		branches, err = s.branchRepo.ListBranches(ctx, tx, tenantID)
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("service: list branches: %w", err)
	}
	return branches, nil
}

func (s *Service) CreateBranch(ctx context.Context, b pub.Branch) (pub.Branch, error) {
	var created pub.Branch
	err := s.db.WithTenantTx(ctx, b.TenantID, func(tx pgx.Tx) error {
		var err error
		created, err = s.branchRepo.CreateBranch(ctx, tx, b)
		return err
	})
	if err != nil {
		return pub.Branch{}, fmt.Errorf("service: create branch: %w", err)
	}

	if err := events.PublishBranchCreated(ctx, s.publisher, created); err != nil {
		s.logger.Warn("branch.created.v1 publish failed",
			zap.String("tenant_id", created.TenantID.String()),
			zap.String("branch_id", created.ID.String()),
			zap.Error(err),
		)
	}
	return created, nil
}

func (s *Service) UpdateBranch(ctx context.Context, b pub.Branch) (pub.Branch, error) {
	var updated pub.Branch
	err := s.db.WithTenantTx(ctx, b.TenantID, func(tx pgx.Tx) error {
		var err error
		updated, err = s.branchRepo.UpdateBranch(ctx, tx, b)
		return err
	})
	if err != nil {
		return pub.Branch{}, wrapNotFound(err, "service: update branch: %w")
	}
	return updated, nil
}

// --- DocumentStore ---

func (s *Service) ListDocuments(ctx context.Context, tenantID uuid.UUID) ([]pub.Document, error) {
	var docs []pub.Document
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		docs, err = s.docRepo.ListDocuments(ctx, tx, tenantID)
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("service: list documents: %w", err)
	}
	return docs, nil
}

func (s *Service) GetDocument(ctx context.Context, tenantID, docID uuid.UUID) (pub.Document, error) {
	var doc pub.Document
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		doc, err = s.docRepo.GetDocument(ctx, tx, tenantID, docID)
		return err
	})
	if err != nil {
		return pub.Document{}, wrapNotFound(err, "service: get document: %w")
	}
	return doc, nil
}

func (s *Service) CreateDocument(ctx context.Context, doc pub.Document) (pub.Document, error) {
	if err := validateDocument(doc); err != nil {
		return pub.Document{}, err
	}
	var created pub.Document
	err := s.db.WithTenantTx(ctx, doc.TenantID, func(tx pgx.Tx) error {
		var err error
		created, err = s.docRepo.CreateDocument(ctx, tx, doc)
		return err
	})
	if err != nil {
		return pub.Document{}, fmt.Errorf("service: create document: %w", err)
	}
	return created, nil
}

func (s *Service) UpdateDocumentStatus(ctx context.Context, tenantID, docID uuid.UUID, status pub.DocumentStatus, note string) error {
	if !validDocumentStatus(status) {
		return pub.ErrInvalid
	}
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.docRepo.UpdateDocumentStatus(ctx, tx, tenantID, docID, status, note)
	})
	if err != nil {
		return wrapNotFound(err, "service: update document status: %w")
	}
	return nil
}

func (s *Service) DeleteDocument(ctx context.Context, tenantID, docID uuid.UUID) error {
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.docRepo.DeleteDocument(ctx, tx, tenantID, docID)
	})
	if err != nil {
		return wrapNotFound(err, "service: delete document: %w")
	}
	return nil
}

func (s *Service) ListBranchDocuments(ctx context.Context, tenantID, branchID uuid.UUID) ([]pub.BranchDocument, error) {
	var docs []pub.BranchDocument
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		docs, err = s.docRepo.ListBranchDocuments(ctx, tx, tenantID, branchID)
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("service: list branch documents: %w", err)
	}
	return docs, nil
}

func (s *Service) CreateBranchDocument(ctx context.Context, doc pub.BranchDocument) (pub.BranchDocument, error) {
	if err := validateBranchDocument(doc); err != nil {
		return pub.BranchDocument{}, err
	}
	var created pub.BranchDocument
	err := s.db.WithTenantTx(ctx, doc.TenantID, func(tx pgx.Tx) error {
		var err error
		created, err = s.docRepo.CreateBranchDocument(ctx, tx, doc)
		return err
	})
	if err != nil {
		return pub.BranchDocument{}, fmt.Errorf("service: create branch document: %w", err)
	}
	return created, nil
}

func (s *Service) UpdateBranchDocumentStatus(ctx context.Context, tenantID, branchID, docID uuid.UUID, status pub.DocumentStatus, note string) error {
	if !validDocumentStatus(status) {
		return pub.ErrInvalid
	}
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.docRepo.UpdateBranchDocumentStatus(ctx, tx, tenantID, branchID, docID, status, note)
	})
	if err != nil {
		return wrapNotFound(err, "service: update branch document status: %w")
	}
	return nil
}

func (s *Service) DeleteBranchDocument(ctx context.Context, tenantID, branchID, docID uuid.UUID) error {
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.docRepo.DeleteBranchDocument(ctx, tx, tenantID, branchID, docID)
	})
	if err != nil {
		return wrapNotFound(err, "service: delete branch document: %w")
	}
	return nil
}

// --- HoursStore ---

func (s *Service) GetRegularHours(ctx context.Context, tenantID, branchID uuid.UUID) ([]pub.RegularHours, error) {
	var hours []pub.RegularHours
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		hours, err = s.hoursRepo.GetRegularHours(ctx, tx, tenantID, branchID)
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("service: get regular hours: %w", err)
	}
	return hours, nil
}

func (s *Service) SetRegularHours(ctx context.Context, tenantID, branchID uuid.UUID, hours []pub.RegularHours) error {
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.hoursRepo.SetRegularHours(ctx, tx, tenantID, branchID, hours)
	})
	if err != nil {
		return fmt.Errorf("service: set regular hours: %w", err)
	}
	return nil
}

func (s *Service) GetSpecialHours(ctx context.Context, tenantID, branchID uuid.UUID) ([]pub.SpecialHours, error) {
	var hours []pub.SpecialHours
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		hours, err = s.hoursRepo.GetSpecialHours(ctx, tx, tenantID, branchID)
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("service: get special hours: %w", err)
	}
	return hours, nil
}

func (s *Service) UpsertSpecialHours(ctx context.Context, tenantID, branchID uuid.UUID, sh pub.SpecialHours) error {
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.hoursRepo.UpsertSpecialHours(ctx, tx, tenantID, branchID, sh)
	})
	if err != nil {
		return fmt.Errorf("service: upsert special hours: %w", err)
	}
	return nil
}

func (s *Service) DeleteSpecialHours(ctx context.Context, tenantID, branchID uuid.UUID, date time.Time) error {
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.hoursRepo.DeleteSpecialHours(ctx, tx, tenantID, branchID, date)
	})
	if err != nil {
		return wrapNotFound(err, "service: delete special hours: %w")
	}
	return nil
}

func (s *Service) IsOpenAt(ctx context.Context, tenantID, branchID uuid.UUID, at time.Time) (bool, error) {
	var open bool
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		open, err = s.hoursRepo.IsOpenAt(ctx, tx, tenantID, branchID, at)
		return err
	})
	if err != nil {
		return false, fmt.Errorf("service: is open at: %w", err)
	}
	return open, nil
}

// --- IntegratorStore ---

func (s *Service) ListIntegrators(ctx context.Context, tenantID uuid.UUID) ([]pub.BillingIntegrator, error) {
	var integrators []pub.BillingIntegrator
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		integrators, err = s.intRepo.ListIntegrators(ctx, tx, tenantID)
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("service: list integrators: %w", err)
	}
	return integrators, nil
}

func (s *Service) GetIntegrator(ctx context.Context, tenantID, integratorID uuid.UUID) (pub.BillingIntegrator, error) {
	var i pub.BillingIntegrator
	err := s.db.WithTenantReadTx(ctx, tenantID, func(tx pgx.Tx) error {
		var err error
		i, err = s.intRepo.GetIntegrator(ctx, tx, tenantID, integratorID)
		return err
	})
	if err != nil {
		return pub.BillingIntegrator{}, wrapNotFound(err, "service: get integrator: %w")
	}
	return i, nil
}

func (s *Service) CreateIntegrator(ctx context.Context, i pub.BillingIntegrator) (pub.BillingIntegrator, error) {
	var created pub.BillingIntegrator
	err := s.db.WithTenantTx(ctx, i.TenantID, func(tx pgx.Tx) error {
		var err error
		created, err = s.intRepo.CreateIntegrator(ctx, tx, i)
		return err
	})
	if err != nil {
		return pub.BillingIntegrator{}, fmt.Errorf("service: create integrator: %w", err)
	}
	return created, nil
}

func (s *Service) UpdateIntegrator(ctx context.Context, i pub.BillingIntegrator) (pub.BillingIntegrator, error) {
	var updated pub.BillingIntegrator
	err := s.db.WithTenantTx(ctx, i.TenantID, func(tx pgx.Tx) error {
		var err error
		updated, err = s.intRepo.UpdateIntegrator(ctx, tx, i)
		return err
	})
	if err != nil {
		return pub.BillingIntegrator{}, wrapNotFound(err, "service: update integrator: %w")
	}
	return updated, nil
}

func (s *Service) DeleteIntegrator(ctx context.Context, tenantID, integratorID uuid.UUID) error {
	err := s.db.WithTenantTx(ctx, tenantID, func(tx pgx.Tx) error {
		return s.intRepo.DeleteIntegrator(ctx, tx, tenantID, integratorID)
	})
	if err != nil {
		return wrapNotFound(err, "service: delete integrator: %w")
	}
	return nil
}

// --- helpers ---

// wrapNotFound returns sentinel errors (ErrNotFound, ErrInvalid) unwrapped so callers
// can use errors.Is. All other errors are wrapped with the supplied format string.
func wrapNotFound(err error, format string) error {
	if errors.Is(err, pub.ErrNotFound) || errors.Is(err, pub.ErrInvalid) {
		return err
	}
	return fmt.Errorf(format, err)
}

// maxDocumentSize is the upper bound for uploaded document file size (50 MB).
const maxDocumentSize int64 = 50 << 20

var allowedMIMETypes = map[string]bool{
	"application/pdf": true,
	"image/jpeg":      true,
	"image/png":       true,
	"image/webp":      true,
}

func validateDocument(doc pub.Document) error {
	if doc.FileKey == "" || doc.FileName == "" {
		return pub.ErrInvalid
	}
	if doc.FileSize <= 0 || doc.FileSize > maxDocumentSize {
		return pub.ErrInvalid
	}
	if !allowedMIMETypes[doc.MimeType] {
		return pub.ErrInvalid
	}
	if !validDocumentTypeStr(string(doc.DocumentType)) {
		return pub.ErrInvalid
	}
	return nil
}

func validateBranchDocument(doc pub.BranchDocument) error {
	if doc.FileKey == "" || doc.FileName == "" {
		return pub.ErrInvalid
	}
	if doc.FileSize <= 0 || doc.FileSize > maxDocumentSize {
		return pub.ErrInvalid
	}
	if !allowedMIMETypes[doc.MimeType] {
		return pub.ErrInvalid
	}
	if !validBranchDocumentTypeStr(string(doc.DocumentType)) {
		return pub.ErrInvalid
	}
	return nil
}

func validDocumentStatus(s pub.DocumentStatus) bool {
	switch s {
	case pub.DocStatusPending, pub.DocStatusVerified, pub.DocStatusRejected, pub.DocStatusExpired:
		return true
	}
	return false
}

func validDocumentTypeStr(s string) bool {
	switch pub.DocumentType(s) {
	case pub.DocVergiLevhasi, pub.DocTicaretSicil, pub.DocImzaSirkuleri,
		pub.DocFaaliyetBelgesi, pub.DocGidaSicil, pub.DocIsyeriAcmaRuhsati, pub.DocOther:
		return true
	}
	return false
}

func validBranchDocumentTypeStr(s string) bool {
	switch pub.BranchDocumentType(s) {
	case pub.BranchDocVergiLevhasi, pub.BranchDocIsyeriRuhsati, pub.BranchDocKiraSozlesmesi,
		pub.BranchDocFranchiseSozlesmesi, pub.BranchDocGidaSicil, pub.BranchDocIsyeriAcmaRuhsati,
		pub.BranchDocYanginGuvenlik, pub.BranchDocSaglikSertifikasi, pub.BranchDocOther:
		return true
	}
	return false
}
