-- Migration: payment/000004_fiscal_adapter_v2
-- ADR-FISCAL-002: asynchronous fiscal registration model (submit + result).
-- Widens payments.method/status to the full POS payment vocabulary and adds
-- the tables needed to submit a sale to a fiscal device/cloud vendor without
-- blocking the payment transaction: fiscal_submissions (outbox-pattern row,
-- one per registration attempt), fiscal_terminals (device registry used to
-- resolve inbound webhooks), fiscal_device_sections (device-synced tax
-- sections) and fiscal_section_mappings (catalog category -> device section).
--
-- Depends on:
--   payment/000001_create_payment — payments table
--   payment/000003_outbox_claim   — claim/retry column pattern reused here

-- ─── payments: widen method/status enums ───────────────────────────────────
-- The original CHECK constraints were unnamed; Postgres assigned the default
-- "<table>_<column>_check" names, so those names can be targeted directly.
ALTER TABLE payments
    DROP CONSTRAINT IF EXISTS payments_method_check,
    DROP CONSTRAINT IF EXISTS payments_status_check;

ALTER TABLE payments
    ADD CONSTRAINT payments_method_check
        CHECK (method IN ('cash', 'terminal', 'meal_card', 'comp', 'no_charge', 'open_account')),
    ADD CONSTRAINT payments_status_check
        CHECK (status IN ('pending', 'completed', 'failed', 'voided'));

-- ─── fiscal_submissions ─────────────────────────────────────────────────────
-- One row per fiscal registration attempt, written in the same transaction as
-- the payment (outbox pattern, ADR-DATA-001). id is generated by the
-- application (no DEFAULT) because it doubles as the vendor-side idempotency
-- reference (Token basketID). A dispatcher/worker calls SubmitSale outside
-- the transaction; the result (sync or async webhook) updates this row via
-- OnFiscalResult.
CREATE TABLE IF NOT EXISTS fiscal_submissions (
    id              UUID        PRIMARY KEY,
    tenant_id       UUID        NOT NULL,
    branch_id       UUID        NOT NULL,
    payment_id      UUID        NOT NULL,
    adapter_type    TEXT        NOT NULL,
    terminal_serial TEXT,
    status          TEXT        NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'submitted', 'completed', 'failed', 'voided', 'expired')),
    sale_payload    JSONB       NOT NULL,
    result_payload  JSONB,
    retry_count     INT         NOT NULL DEFAULT 0,
    next_retry_at   TIMESTAMPTZ,
    last_error      TEXT,
    claimed_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    submitted_at    TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ
);

-- Dispatcher scan order: oldest unsubmitted rows first.
CREATE INDEX IF NOT EXISTS fiscal_submissions_dispatchable_idx
    ON fiscal_submissions (created_at) WHERE status = 'pending';

-- Reconciliation / lookup by payment within a tenant.
CREATE INDEX IF NOT EXISTS fiscal_submissions_tenant_payment_idx
    ON fiscal_submissions (tenant_id, payment_id);

-- Reconciler sweep: submitted rows whose webhook never arrived, oldest first.
-- Partial on status so the index stays tiny relative to the append-only table.
CREATE INDEX IF NOT EXISTS fiscal_submissions_stale_submitted_idx
    ON fiscal_submissions (submitted_at) WHERE status = 'submitted';

-- At most one in-flight submission per payment; a payment can be retried by
-- moving the failed row aside (status update), never by inserting a second
-- pending/submitted row for the same payment.
CREATE UNIQUE INDEX IF NOT EXISTS fiscal_submissions_active_payment_idx
    ON fiscal_submissions (payment_id) WHERE status IN ('pending', 'submitted');

ALTER TABLE fiscal_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiscal_submissions FORCE ROW LEVEL SECURITY;

CREATE POLICY fiscal_submissions_tenant_isolation ON fiscal_submissions
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', TRUE), '')::uuid);

-- The submission worker claims rows across every tenant in one scan
-- (db.WithAllTenantsTx sets app.tenant_scope = 'all_tenants'; see
-- tenant/000004 and identity/000008 for the same pattern). The claim is an
-- UPDATE (sets claimed_at), so both SELECT and UPDATE need the scope branch.
-- INSERT deliberately gets none: submissions are only written tenant-scoped,
-- in the same transaction as their payment.
CREATE POLICY fiscal_submissions_all_tenants_select ON fiscal_submissions
    FOR SELECT TO app_runtime
    USING (current_setting('app.tenant_scope', TRUE) = 'all_tenants');

CREATE POLICY fiscal_submissions_all_tenants_claim ON fiscal_submissions
    FOR UPDATE TO app_runtime
    USING (current_setting('app.tenant_scope', TRUE) = 'all_tenants')
    WITH CHECK (current_setting('app.tenant_scope', TRUE) = 'all_tenants');

GRANT SELECT, INSERT, UPDATE ON fiscal_submissions TO app_runtime;

-- ─── fiscal_terminals ───────────────────────────────────────────────────────
-- Device registry. Registered from the admin panel by scanning the device QR
-- (merchantId_branchId_terminalId). Used both to resolve which terminal a
-- POS payment should target and to resolve an inbound vendor webhook back to
-- a tenant/branch (ADR-FISCAL-002 §5).
CREATE TABLE IF NOT EXISTS fiscal_terminals (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID        NOT NULL,
    branch_id           UUID        NOT NULL,
    vendor              TEXT        NOT NULL,           -- e.g. 'tokenx'
    terminal_serial     TEXT        NOT NULL,            -- e.g. 'AV0000000658'
    vendor_merchant_ref TEXT,
    vendor_branch_ref   TEXT,
    label               TEXT,
    basket_mode         TEXT        NOT NULL DEFAULT 'instant'
        CHECK (basket_mode IN ('instant', 'list')),
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS fiscal_terminals_tenant_vendor_serial_idx
    ON fiscal_terminals (tenant_id, vendor, terminal_serial);

-- A webhook arrives with only the vendor's own terminal identifier and no
-- tenant context; (vendor, terminal_serial) alone must resolve to exactly
-- one registry row across all tenants, so it is also globally unique.
CREATE UNIQUE INDEX IF NOT EXISTS fiscal_terminals_vendor_serial_idx
    ON fiscal_terminals (vendor, terminal_serial);

ALTER TABLE fiscal_terminals ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiscal_terminals FORCE ROW LEVEL SECURITY;

CREATE POLICY fiscal_terminals_tenant_isolation ON fiscal_terminals
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', TRUE), '')::uuid);

GRANT SELECT, INSERT, UPDATE ON fiscal_terminals TO app_runtime;

-- ─── fiscal_device_sections ─────────────────────────────────────────────────
-- Tax sections synced from the device itself (Get Fiscal Parameters /
-- getFiscalInfo). terminal_id is a bare UUID reference to fiscal_terminals.id
-- (no FK — same intra-module, no-cross-table-FK pattern as payments.check_id).
CREATE TABLE IF NOT EXISTS fiscal_device_sections (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID        NOT NULL,
    terminal_id   UUID        NOT NULL,
    section_no    INT         NOT NULL,
    name          TEXT        NOT NULL,
    tax_permyriad INT         NOT NULL,
    synced_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS fiscal_device_sections_terminal_section_idx
    ON fiscal_device_sections (tenant_id, terminal_id, section_no);

ALTER TABLE fiscal_device_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiscal_device_sections FORCE ROW LEVEL SECURITY;

CREATE POLICY fiscal_device_sections_tenant_isolation ON fiscal_device_sections
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', TRUE), '')::uuid);

-- Full sync workflow (add/replace/remove sections on each device refresh)
-- needs DELETE in addition to the usual DML set.
GRANT SELECT, INSERT, UPDATE, DELETE ON fiscal_device_sections TO app_runtime;

-- ─── fiscal_section_mappings ────────────────────────────────────────────────
-- Admin-configured mapping from a catalog category to a device tax section.
-- sectionNo/taxPercent are never hardcoded in application code (ADR-FISCAL-002
-- §2); this table is the only source of truth for that mapping.
CREATE TABLE IF NOT EXISTS fiscal_section_mappings (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID        NOT NULL,
    branch_id   UUID        NOT NULL,
    category_id UUID        NOT NULL,
    section_no  INT         NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS fiscal_section_mappings_branch_category_idx
    ON fiscal_section_mappings (tenant_id, branch_id, category_id);

ALTER TABLE fiscal_section_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiscal_section_mappings FORCE ROW LEVEL SECURITY;

CREATE POLICY fiscal_section_mappings_tenant_isolation ON fiscal_section_mappings
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', TRUE), '')::uuid);

GRANT SELECT, INSERT, UPDATE ON fiscal_section_mappings TO app_runtime;
